#!/usr/bin/env python3
"""Generate a C-loadable chirp-in-noise test signal and diagnostic plot."""

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


SAMPLE_RATE_HZ = 48_000
XCORR_DECIMATION_FACTOR = 6
XCORR_SAMPLE_RATE_HZ = SAMPLE_RATE_HZ // XCORR_DECIMATION_FACTOR
DURATION_SECONDS = 10
CHIRP_START_SECONDS = 5.0
CHIRP_DURATION_SECONDS = 0.100
CHIRP_START_FREQUENCY_HZ = 100.0
CHIRP_END_FREQUENCY_HZ = 800.0
CHIRP_AMPLITUDE = 0.70
NOISE_STANDARD_DEVIATION = 0.04
RANDOM_SEED = 20260912

DATA_DIRECTORY = Path(__file__).resolve().parent / "data"
PCM_OUTPUT_PATH = DATA_DIRECTORY / "chirp_noise_48khz_s16le.pcm"
PLOT_OUTPUT_PATH = DATA_DIRECTORY / "chirp_noise_48khz.png"
CHIRP_HEADER_OUTPUT_PATH = (
    Path(__file__).resolve().parents[2] / "Core" / "Src" / "pp_chirp_signal.h"
)
CHIRP_HEADER_SAMPLES_PER_LINE = 12


def generate_chirp_signal():
    """Return the standalone linear chirp as normalized float samples."""
    chirp_sample_count = int(CHIRP_DURATION_SECONDS * SAMPLE_RATE_HZ)
    chirp_time_seconds = np.arange(chirp_sample_count) / SAMPLE_RATE_HZ
    chirp_rate_hz_per_second = (
        CHIRP_END_FREQUENCY_HZ - CHIRP_START_FREQUENCY_HZ
    ) / CHIRP_DURATION_SECONDS
    chirp_phase_radians = 2.0 * np.pi * (
        CHIRP_START_FREQUENCY_HZ * chirp_time_seconds
        + 0.5 * chirp_rate_hz_per_second * chirp_time_seconds**2
    )

    return CHIRP_AMPLITUDE * np.sin(chirp_phase_radians)


def quantize_to_pcm16(signal):
    """Convert normalized samples to signed 16-bit PCM."""
    return np.rint(np.clip(signal, -1.0, 1.0) * np.iinfo(np.int16).max).astype(
        np.int16
    )


def downsample_chirp_for_xcorr(chirp_signal):
    """Match pp_dsp.c's anti-aliasing and factor-six decimation sequence."""
    chirp_pcm = quantize_to_pcm16(chirp_signal)
    anti_aliased_chirp = chirp_pcm.copy()
    neighboring_sums = (
        chirp_pcm[1:].astype(np.int32) + chirp_pcm[:-1].astype(np.int32)
    )
    anti_aliased_chirp[1:] = np.trunc(neighboring_sums / 2.0).astype(np.int16)

    return anti_aliased_chirp[::XCORR_DECIMATION_FACTOR]


def generate_signal():
    """Return a 10-second float signal containing noise and one linear chirp."""
    sample_count = SAMPLE_RATE_HZ * DURATION_SECONDS
    signal = np.random.default_rng(RANDOM_SEED).normal(
        scale=NOISE_STANDARD_DEVIATION, size=sample_count
    )

    chirp_start_sample = int(CHIRP_START_SECONDS * SAMPLE_RATE_HZ)
    chirp_signal = generate_chirp_signal()
    chirp_end_sample = chirp_start_sample + chirp_signal.size
    signal[chirp_start_sample:chirp_end_sample] += chirp_signal

    return signal


def save_chirp_header(chirp_pcm):
    """Write downsampled chirp PCM as a C header shared by both C targets."""
    sample_rows = []
    for start_index in range(0, chirp_pcm.size, CHIRP_HEADER_SAMPLES_PER_LINE):
        samples = chirp_pcm[start_index : start_index + CHIRP_HEADER_SAMPLES_PER_LINE]
        sample_rows.append("    " + ", ".join(str(int(sample)) for sample in samples) + ",")

    header = "\n".join(
        (
            "/* Generated by tools/filter_sim/generate_chirp_noise.py. */",
            "#ifndef SRC_PP_CHIRP_SIGNAL_H_",
            "#define SRC_PP_CHIRP_SIGNAL_H_",
            "",
            "#include <stdint.h>",
            "",
            f"#define PP_CHIRP_SIGNAL_SAMPLE_RATE_HZ {XCORR_SAMPLE_RATE_HZ}U",
            f"#define PP_CHIRP_SIGNAL_DECIMATION_FACTOR {XCORR_DECIMATION_FACTOR}U",
            f"#define PP_CHIRP_SIGNAL_SAMPLE_COUNT {chirp_pcm.size}U",
            "",
            "static const int16_t pp_chirp_signal[PP_CHIRP_SIGNAL_SAMPLE_COUNT] = {",
            *sample_rows,
            "};",
            "",
            "#endif /* SRC_PP_CHIRP_SIGNAL_H_ */",
            "",
        )
    )
    CHIRP_HEADER_OUTPUT_PATH.write_text(header, encoding="ascii")


def save_plot(signal):
    """Save a whole-signal view, chirp detail, and spectrogram."""
    time_seconds = np.arange(signal.size) / SAMPLE_RATE_HZ
    chirp_window_start = CHIRP_START_SECONDS - 0.025
    chirp_window_end = CHIRP_START_SECONDS + CHIRP_DURATION_SECONDS + 0.025
    chirp_mask = (time_seconds >= chirp_window_start) & (
        time_seconds <= chirp_window_end
    )

    figure, (overview_axis, detail_axis, spectrogram_axis) = plt.subplots(
        3, 1, figsize=(11, 9)
    )
    overview_axis.plot(time_seconds, signal, linewidth=0.35)
    overview_axis.set_title("10 s Chirp-in-Noise Signal")
    overview_axis.set_ylabel("Amplitude")
    overview_axis.grid(True, linestyle=":")

    detail_axis.plot(time_seconds[chirp_mask], signal[chirp_mask], linewidth=0.6)
    detail_axis.set_title("Chirp Detail")
    detail_axis.set_xlabel("Time (s)")
    detail_axis.set_ylabel("Amplitude")
    detail_axis.grid(True, linestyle=":")

    spectrogram_axis.specgram(signal, NFFT=1024, Fs=SAMPLE_RATE_HZ, noverlap=768)
    spectrogram_axis.set_title("Spectrogram")
    spectrogram_axis.set_xlabel("Time (s)")
    spectrogram_axis.set_ylabel("Frequency (Hz)")
    spectrogram_axis.set_ylim(0, 10_000)

    figure.tight_layout()
    figure.savefig(PLOT_OUTPUT_PATH, dpi=160)
    plt.close(figure)


def main():
    signal = generate_signal()
    chirp_signal = generate_chirp_signal()
    pcm_signal = quantize_to_pcm16(signal).astype("<i2")
    xcorr_chirp_signal = downsample_chirp_for_xcorr(chirp_signal)

    DATA_DIRECTORY.mkdir(parents=True, exist_ok=True)
    pcm_signal.tofile(PCM_OUTPUT_PATH)
    save_chirp_header(xcorr_chirp_signal)
    save_plot(signal)

    print(f"Wrote {pcm_signal.size} mono samples to {PCM_OUTPUT_PATH}")
    print(
        f"Wrote {xcorr_chirp_signal.size} downsampled chirp samples to "
        f"{CHIRP_HEADER_OUTPUT_PATH}"
    )
    print(f"Wrote plot to {PLOT_OUTPUT_PATH}")


if __name__ == "__main__":
    main()